language: c
dist: bionic

branches:
  only:
    - master

matrix:
  include:
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
  - os: osx
    compiler: clang
    osx_image: xcode11.3
  - os: osx
    compiler: /usr/local/bin/gcc-9
    osx_image: xcode11.3

script:
  - make
  - make test
